I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/park/junction.rpy", line 49, in script
    if seen_bulletin == True:
  File "game/scripts/park/junction.rpy", line 49, in <module>
    if seen_bulletin == True:
NameError: name 'seen_bulletin' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/park/junction.rpy", line 49, in script
    if seen_bulletin == True:
  File "C:\Users\Panko\Desktop\RenPy\renpy\ast.py", line 2086, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Panko\Desktop\RenPy\renpy\python.py", line 904, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Panko\Desktop\RenPy\renpy\python.py", line 897, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/park/junction.rpy", line 49, in <module>
    if seen_bulletin == True:
NameError: name 'seen_bulletin' is not defined

Windows-10-10.0.22000
Ren'Py 8.0.0.22040201n
Visually Daunting 0.01
Mon Apr  4 03:20:46 2022
