I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/park/park_intro.rpy", line 6, in script
    show donovan forward_smile xpos .1
Exception: Image 'donovan forward_smile' does not accept attributes 'xpos .1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/park/park_intro.rpy", line 6, in script
    show donovan forward_smile xpos .1
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'donovan forward_smile' does not accept attributes 'xpos .1'.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
Visually Daunting 0.01
Sat Mar 12 23:51:45 2022
